[package]
name = "anti-anti-ananas"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
actix-rt = "2.8"
actix-files = "0.6"
actix-cors = "0.6"
rand = "0.8"
anyhow = "1.0"
serde = { version = "1.0", features = [ "derive"]}

[profile.release]
lto = "fat"
codegen-units = 1