version: '3'
services:
  app:
    image: ghcr.io/j-brn/anti-anti-ananas.club:latest
    environment:
      - LISTEN_ADDRESS=0.0.0.0:3000
      - MESSAGE_FILE=./messages.txt
      - VIRTUAL_HOST=anti-anti-ananas.club
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=anti-anti-ananas.club

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'
    networks:
      - proxynet

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - letsencrypt_acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:
  letsencrypt_acme:

networks:
  proxynet:
    external: true